# 开发环境
@hostname = fzmall.yjbtest.com;

#仿真环境
# @hostname = devmall.yjbtest.com:8443

### test 1
https://{{hostname}}/mall/api/CRH-MALLY005?rnd=1609219943516&location=1


### test2
POST  https://{{hostname}}/mall/api/CRH-MALLY011?rnd=1609219943298
Content-Type: application/json

{
    "client_id": "",
    "financial_types": "2,3,4,1,5",
    "location": 1,
    "risk_level": "0"
}

### 


